version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "sudo apt-get install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip"
      - "unzip terraform_0.14.7_linux_amd64.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init 
      - terraform plan
  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'