version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "sudo apt-get install unzip -y"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_0.12.2_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init 
      - terraform plan
  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'